language: node_js
node_js:
  - "0.12"
  - "2"
  - "3"
  - "4.2"

branches:
  only:
  	- 4game-dist

env:
  matrix:
    - USE_LATEST_NODE_GYP=true
    - USE_LATEST_NODE_GYP=false

before_install:
  - if [ $USE_LATEST_NODE_GYP == 'true' ]; then npm explore npm -g -- npm install node-gyp@latest; fi;

 after_success:
  - npm install innovaco/libxslt-distribute
  - ./node_modules/.bin/libxslt-distribute .

sudo: false