sudo: required
dist: trusty
language: node_js
node_js:
  - "4.2"

branches:
  only:
    - 4game-dist

# env:
#   matrix:
#     - USE_LATEST_NODE_GYP=true
#     - USE_LATEST_NODE_GYP=false

before_install:
  - npm install -g node-gyp

after_success:
  - 'npm install innovaco/libxslt-distribute'
  - './node_modules/.bin/libxslt-distribute .'
