environment:
  PUBLISH_TOKEN:
    secure: Huxwr+cln7xiX3UL31rYmRDxkQ/J5jzKmfQVKfqAnqasKjdnJf36Hao7fpWNJwuu
  matrix:
  - nodejs_version: "4"
  - nodejs_version: "5"
  - nodejs_version: "6"

os: Visual Studio 2013

platform:
- x86
- x64

branches:
  only:
  - 4game-dist

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node --version
  - npm --version
  - git submodule update --init --recursive

build_script:
  - npm install

test_script:
  - npm test

on_success:
  - npm install innovaco/libxslt-distribute
  - './node_modules/.bin/libxslt-distribute .'

deploy: off
