environment:
 matrix:
  # - nodejs_version: "0.12"
  # - nodejs_version: "2"
  # - nodejs_version: "3"
  # - nodejs_version: "4.0"
  # - nodejs_version: "4.1"
  - nodejs_version: "4.2"
  # - nodejs_version: "5.0"
  # - nodejs_version: "5.1"

os: Visual Studio 2015

platform:
- x86
- x64

branches:
  only:
  - 4game-dist

environment:
  PUBLISH_TOKEN:
    secure: Huxwr+cln7xiX3UL31rYmRDxkQ/J5jzKmfQVKfqAnqasKjdnJf36Hao7fpWNJwuu

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - git submodule update --init --recursive

build_script:
  - npm install

test_script:
  - npm test

deploy_script:
- ps: >-
    npm install innovaco/libxslt-distribute
    ./node_modules/.bin/libxslt-distribute .
